### ISSUE TITLE
Option to change the note sound to guitar notes type

### ISSUE THREAD

**Issue by Iali99** [MaelDrapier/MusicalBeeps#2]
Presently the notes sound like from an organ instrument. Is it possible to modify the audio metadata and make it sound like a guitar note?

**Comment by MaelDrapier** [comment]
In this project, the notes are actually beeps created with [simpleaudio](https://pypi.org/project/simpleaudio/) from calculated frequencies, so it is not possible to make it sound like a guitar or another musical instrument.

As it is not planned for now to add a way to modify how the notes sound, I close this issue.
